version: '3.8'

services:
  frontend:
    build:
      dockerfile: Dockerfile.frontend
    ports:
      - 5173:80
    depends_on:
      - backend
  db:
    image: postgres
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - 5432:5432

  backend:
    build:
      dockerfile: Dockerfile.backend
    ports:
      - 8000:8000
    command: >
      sh -c "
        alembic upgrade head &&
        uvicorn main:app --host 0.0.0.0 --port 8000
      "
    depends_on:
      - db




