"""empty message

Revision ID: 95723171091d
Revises: 5fab9170d125
Create Date: 2025-07-02 12:00:08.717694

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '95723171091d'
down_revision: Union[str, Sequence[str], None] = '5fab9170d125'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('health_check_history', sa.Column('related_address', sa.String(), nullable=False))
    op.create_foreign_key(None, 'health_check_history', 'host_addresses', ['related_address'], ['ip_address'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'health_check_history', type_='foreignkey')
    op.drop_column('health_check_history', 'related_address')
    # ### end Alembic commands ###
